[package]
name = "web_learning"
version = "0.1.0"
edition = "2024"

[dependencies]


actix-web = { version = "4", features = ["openssl"] }

openssl = { version = "0.10" } #这是为了让网站支持https
serde = { version = "1.0" ,features = ["derive"]} # 添加 serde 依赖
serde_json = "1.0" # 添加 serde_json 依赖